<template><section class="page"><PageHeader title="家属共享" eyebrow="异常提醒与报告" :back="true"/><div class="glass rounded-2xl p-4 mb-4"><h2 class="font-semibold">添加家属</h2><form class="mt-3 space-y-3" @submit.prevent="add"><input v-model="contact" required class="input" placeholder="手机号或邮箱"/><input v-model="relationship" required class="input" placeholder="关系，例如：女儿"/><button class="btn-primary" :disabled="saving">{{ saving?'添加中…':'发送共享邀请' }}</button></form></div><p v-if="error" class="text-sm text-[#ff3b30] mb-3">{{ error }}</p><div class="space-y-3"><div v-for="item in items" :key="String(item.id)" class="glass rounded-2xl p-4 flex items-center gap-3"><span class="w-10 h-10 rounded-xl bg-[#eaf4ff] text-[#0a84ff] grid place-items-center"><i class="fa-solid fa-user-group"/></span><div class="flex-1"><p class="font-medium text-sm">{{ item.contact }}</p><p class="text-xs muted mt-1">{{ item.relationship }} · {{ item.status==='pending'?'待确认':'已连接' }}</p></div><button class="text-xs text-[#ff3b30]" @click="remove(String(item.id))">移除</button></div></div><div v-if="!items.length&&!error" class="glass rounded-2xl p-6 text-center muted text-sm">暂未添加家属</div></section></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import PageHeader from '../components/PageHeader.vue'; import { apiClient } from '../services/api'
const items=ref<Array<Record<string,unknown>>>([]);const contact=ref('');const relationship=ref('');const saving=ref(false);const error=ref('')
async function load(){try{items.value=await apiClient.family()}catch(e){error.value=e instanceof Error?e.message:'家属列表加载失败'}}
async function add(){saving.value=true;error.value='';try{const item=await apiClient.createFamily({contact:contact.value.trim(),relationship:relationship.value.trim(),permissions:['critical_alerts','weekly_report']});items.value.unshift(item);contact.value='';relationship.value=''}catch(e){error.value=e instanceof Error?e.message:'邀请发送失败'}finally{saving.value=false}}
async function remove(id:string){try{await apiClient.deleteFamily(id);items.value=items.value.filter(x=>String(x.id)!==id)}catch(e){error.value=e instanceof Error?e.message:'移除失败'}}
onMounted(load)
</script>
